services:
  vprodb:
    build: 
      context: ./Docker-files/db
      image: deepaktyagi048/vprofiledb
      container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql

  vprocache01:
    build:
      image: memcached
      ports:
        - "11211:11211"

  vpromq01:
    build:
      image: rabbitmq
      ports:
        - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    build: 
      context: ./Docker-files/app
      image: deepaktyagi048/vprofileapp
      container-name: vproapp    
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps/

  vproweb:
    build: 
      context: ./Docker-files/web
      image: deepaktyagi048/vprofileweb
      container-name: vproweb   
    ports:
      - "80:80"


volumes:
   vprodbdata: {}
   vproappdata: {}